default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: study-app_development

test:
  <<: *default
  database: study-app_test

production:
  <<: *default
  adapter: postgresql
  encoding: utf8
  database: studyapp-postgresql
  username: <%= ENV["PRODUCTION_DB_USER_NAME"] %>
  password: <%= ENV["PRODUCTION_DB_PASSWORD"] %>
  host: <%= ENV["PRODUCTION_DB_HOST"] %>
  port: 5432
