default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: study-app_development

test:
  <<: *default
  database: study-app_test

production:
  <<: *default
  adapter: postgresql
  encoding: utf8
  database: studyapp-postgresql
  username: postgres
  password: sakura3c
  host: studyapp-postgresql.cdka7whdrybp.ap-northeast-1.rds.amazonaws.com
  port: 5432
